- hosts: dev
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: sowparnika268/my-python-app:latest
        tag: latest
        source: pull

    - name: Stop existing container
      docker_container:
        name: my-python-app
        state: absent

    - name: Run container
      docker_container:
        name: my-python-app
        image: sowparnika268/my-python-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"

