- hosts: all
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: latest
        source: pull

    - name: Stop existing container
      docker_container:
        name: my-python-app
        state: absent

    - name: Run container
      docker_container:
        name: my-python-app
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"

