- name: Configure EC2 Instance and Deploy Docker Container
  hosts: ec2
  become: yes
  vars:
    docker_image: "my_web_app"  
    docker_port: 5000  

  tasks:
    - name: Install necessary packages
      apt:
        name: 
          - python3-pip
          - docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install necessary packages
      yum:
        name: 
          - python3-pip
          - docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: latest
        source: pull

    - name: Run the Docker container
      docker_container:
        name: my_web_app_container
        image: "{{ docker_image }}"
        state: started
        ports:
          - "{{ docker_port }}:5000"  
