- hosts: dev
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: latest
        source: pull

    - name: Stop existing container if running
      docker_container:
        name: my-python-app
        state: stopped
      when: ansible_facts['docker_containers'] | selectattr('Names', 'search', 'my-python-app') | list | length > 0

    - name: Run container
      docker_container:
        name: my-python-app
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
