name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Deploy to Dev EC2
        uses: appleboy/ssh-action@master
        with:
          host: 3.108.61.107
          username: ubuntu  # Change if needed
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to the app directory or clone the repository if it doesn't exist
            if [ ! -d "/home/ubuntu/my-python-app" ]; then
              git clone https://github.com/Sowparnika-Poojary/Python_Web_App.git /home/ubuntu/my-python-app
            fi
            
            cd /home/ubuntu/my-python-app
            
            # Pull latest changes
            git pull
            
            # Build Docker image
            docker build -t sowparnika268/my-python-app:latest .

            #Push Docker image to Docker Hub
            docker push sowparnika268/my-python-app:latest
            
            # Stop and remove the existing container if it's running
            if [ $(docker ps -q -f name=my-python-app) ]; then
              docker stop my-python-app
              docker rm mypython-app
            fi
            
            # Run the Docker container
            docker run -d -p 80:80 --name my-python-app myapp:latest
