name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t sowparnika268/my-python-app:latest .

      - name: Run tests
        run: |
          echo "Running tests..."

      - name: Push Docker image to Docker Hub
        run: docker push sowparnika268/my-python-app:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          ssh-keyscan -H 43.204.38.42 >> ~/.ssh/known_hosts

      # Copy Ansible Playbook and Inventory to the Server
      - name: Copy Playbook and Inventory
        run: |
          scp -o StrictHostKeyChecking=no ansible/configuration.yml ubuntu@43.204.38.42:/tmp/playbook.yml
          scp -o StrictHostKeyChecking=no ansible/hosts ubuntu@43.204.38.42:/tmp/inventory

      # Run Ansible Playbook on the Server
      - name: Run Ansible Playbook
        run: |
          ssh ubuntu@43.204.38.42 "ansible-playbook -i /tmp/inventory /tmp/playbook.yml"

      - name: Cleanup
        run: |
          ssh user@your.dev.server.ip "rm -f /tmp/playbook.yml /tmp/inventory"

